"""AWOL Vision Aetherion Max IR codes learned from the stock remote.

Protocol: NEC-like, 38 kHz carrier.
Codes are stored as base64-encoded Broadlink IR packets, converted to
raw microsecond timings at runtime for the infrared platform.
"""

from __future__ import annotations

import base64
from enum import Enum
from typing import override

from infrared_protocols import Command

CARRIER_FREQ_HZ = 38_000

_TICK_US = 8192.0 / 269.0


def _broadlink_b64_to_timings(b64: str) -> list[int]:
    """Convert a base64 Broadlink IR packet to signed µs timings."""
    packet = base64.b64decode(b64)
    if len(packet) < 4 or packet[0] != 0x26:
        raise ValueError(f"Invalid Broadlink IR packet (type=0x{packet[0]:02X})")

    length = packet[2] | (packet[3] << 8)
    data = packet[4:4 + length]

    timings: list[int] = []
    i = 0
    is_pulse = True
    while i < len(data):
        if data[i] == 0x00 and i + 2 < len(data):
            ticks = (data[i + 1] << 8) | data[i + 2]
            i += 3
        else:
            ticks = data[i]
            i += 1

        if ticks == 0:
            break

        us = round(ticks * _TICK_US)
        timings.append(us if is_pulse else -us)
        is_pulse = not is_pulse

    return timings


class AetherionCode(Enum):
    """IR command codes for the AWOL Vision Aetherion Max.

    Values are base64-encoded Broadlink IR packets learned from the stock remote.
    """

    POWER = "JgBQAAABI5QQExETEBMQExATEBMQExATEBMQOBA4EDgQExATEDgQOBATEDgQExA4EDgQExATEBMQOBAUEDgQExATEDgQOBA4EAAFnwABJUoQAA0E"
    AI = "JgBQAAABJJQQExATEBMQExATEBMQExATEBMQOBA4EDgQExATEDgQOBATEDgQExA4EDgQExA4EDgQOBATEDgQExATEDgQExATEAAFnwABJUoQAA0E"
    MUTE = "JgBYAAABJpQQExATEBMQExATEBMQExATEBMQOBA4EDgQExATEDgQOBA4EDgQExA4EDgQExATEBMQExATEDgQExATEDgQOBA4EAAFnwABJUoQAAxSAAEmShAADQQ="
    INPUT_SOURCE = "JgBQAAABJZQQExATEBMQExATEBMQExATEBMQOBA4EDgQExATEDgQOBATEDgQExATEDgQExATEBMQOBATEDgQOBATEDkQOBA4EAAFnwABJUoQAA0E"
    PROFILE = "JgBQAAABJpQQExATEBMQExATEBMQExATEBMQOBA4EDgQExATEDgQOBATEBMQExA4EDgQExA4EDgQOBA4EDgQExAWDTgQExATEAAFnwABJUoQAA0E"
    GOOGLE_ASSISTANT = "JgBQAAABJZQQExATEBMQExATEBMQExATEBMQOBA4EDgQExATEDgQOBA4EBMQExATEBMQOBA4EDgQExA4EDgQOBA4EBMQExATEAAFnwABJUoQAA0E"
    SETTINGS = "JgBQAAABIpQQExATEBMQExATEBMQExATEBMQOBA4EDgQExATEDgQOBA4EDgQOBA4EBMQExATEBMQExAUEBMQFBA4EDgQOBA4EAAFnwABJUoQAA0E"
    UP = "JgBQAAABJpQQExATEBMQExATEBMQExATEBMQPAw4EDgQExATEDgQOBATEDgQOBATEBMQOBATEBMQOBATEBMQOBA4EBMQOBA4EAAFnwABJUoQAA0E"
    DOWN = "JgBQAAABJJQQExATEBMQExATEBMQExATEBMQOBA4EDgQExATEDgQOBA4EDgQOBATEBMQOBATEBMQExATEBMQOBA4EBMQOBA4EAAFnwABJUoQAA0E"
    LEFT = "JgBQAAABJpQQExATEBMQExATEBMQExATEBMQOBA4EDgQExATEDgQOBATEBMQOBATEBMQOBATEBMQOBA4EBMQOBA4EBMQOBA4EAAFnwABJUoQAA0E"
    RIGHT = "JgBQAAABJZQQFBATEBMQExATEBMQExATEBMQOBA4EDgQExATEDgQOBA4EBMQOBATEBMQOBATEBMQExA4EBMQOBA4EBMQOBA4EAAFnwABJUoQAA0E"
    OK = "JgBQAAABJJQQExATEBMQExATEBMQExATEBMSNhA4EDgQExATEDgQOBATEBMQExA4EBMQOBATERIQOBA4EDgQExA4EBMQOBA5EAAFnwABJUoQAA0E"
    BACK = "JgBQAAABJZQQExATEBMQFA8TEBMQExATEBMQOBA4EDgQExAUEDgQOBAUDxMQOBA4EDgQExA4EBMQOBA4EBMQExATEDgQExA4EAAFnwABJUoQAA0E"
    HOME = "JgBQAAABJpQQExATEBMQExATEBMQExATEBMQOBA4EDgQExATEDgQOBA4EDgQExA4EDgQExA4EBMQExATEDgQExATEDgQExA4EAAFnwABJUoQAA0E"
    LIVE_GUIDE = "JgBQAAABJZQQExATEBMQExATEBMQExATEBMQOBA4EDgQExATEDgQOBATEDgQExATEBMQOBA4EDgQOBATEDgQOBA4EBMQExATEAAFnwABJUoQAA0E"
    LIVE_TV = "JgBYAAABJZQQExATEBMQExATEBMQFA8TEBMQOBA4EDgQFA8TEDgQOBATEBMQOBA4EBMQOBA4EDgQOBA4EBQPExA4EBQQFA8UDwAFnwABJUoQAAxSAAEmShAADQQ="
    MENU = "JgBQAAABJpQQExATEBMQExATEBMQExATEBMQOBA4EDgQExATEDgQOBATEDgQExA4EDgQExA4EBMQOBATEDgQExATEDgQExA4EAAFnwABJUoQAA0E"
    VOLUME_DOWN = "JgBQAAABJZQQExATEBMQExATEBMQExATEBMQOBA4EDgQExATEDgQOBA4EDgQExA4EBMQExATEBMQExATEDgQExA4EDgQOBA4EAAFnwABJUoQAA0E"
    VOLUME_UP = "JgBQAAABJZQQExATEBMQExATEBMQExATEBMQOBA4EDgQExATEDgQOBATEDgRExA4EBMQExATEBMQOBATEDgQExA4EDgQOBA4EAAFnwABJUoQAA0E"
    YOUTUBE = "JgBQAAABJJQQExATEBMQExATEBMQExATEBMQOBA4EDgQExATEDgQOBA4EDgQExA4EDgQExA4EDgQExATEDgQExATEDgQExATEAAFnwABJUoQAA0E"
    NETFLIX = "JgBQAAABI5MQExATERMQExATEBMQExATEBMQOBA4EDgQExATEDgQOBATEBMQOBA4EDgQExA4EDgQOBA4EBMQExATEDgQExATEAAFnwABJUoQAA0E"
    PRIME_VIDEO = "JgBQAAABJZQQExATEBMQExATEBMQExATEBMQOBA4EDgQExATEDgQOBA4EBMQOBA4EDgQExA4EDgQExA4EBMQExAUDzgQFA8UDwAFnwABJUoQAA0E"
    DISNEY_PLUS = "JgBQAAABJJQQExATEBMQExATEBMQExATEBMQOBA4EDgQExATEDgQOBATEDgQOBA4EDgQExA4EDgQOBATEBMQExATEDgQExATEAAFnwABJUoQAA0E"


class AetherionCommand(Command):
    """IR command for the AWOL Vision Aetherion Max."""

    def __init__(self, code: AetherionCode) -> None:
        super().__init__(modulation=CARRIER_FREQ_HZ, repeat_count=0)
        self._code = code
        self._timings: list[int] | None = None

    @override
    def get_raw_timings(self) -> list[int]:
        if self._timings is None:
            self._timings = _broadlink_b64_to_timings(self._code.value)
        return self._timings
